
[workspace]
resolver = '2'
members = [
	'apps//rust/oop',
	'apps//rust/ownership_mistakes',
	'apps//rust/minigrep',
	'apps//rust/slice',
	'apps//rust/structs',
	'apps//rust/enums',
	'apps//rust/lib',
	'apps//rust/ds',
]

[profile.release]
lto = true
